config/routes.rb
DerivativeD::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  resources :linkedin_transitions

   match ':controller(/:action(/:id))(.:format)'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
  end
  
end

app/models/linkedin_transition.rb
class LinkedinTransition < ActiveRecord::Base
  attr_accessible :from_company_id, :from_company_industry, :from_company_name, :from_company_position, :joined_date, :profile_id, :to_company_id, :to_company_industry, :to_company_name, :to_company_position
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/linkedin_transitions_controller.rb
class LinkedinTransitionsController < ApplicationController
  # GET /linkedin_transitions
  # GET /linkedin_transitions.json
  def index
    @linkedin_transitions = LinkedinTransition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @linkedin_transitions }
    end
  end

  # GET /linkedin_transitions/1
  # GET /linkedin_transitions/1.json
  def show
    @linkedin_transition = LinkedinTransition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @linkedin_transition }
    end
  end

  # GET /linkedin_transitions/new
  # GET /linkedin_transitions/new.json
  def new
    @linkedin_transition = LinkedinTransition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @linkedin_transition }
    end
  end

  # GET /linkedin_transitions/1/edit
  def edit
    @linkedin_transition = LinkedinTransition.find(params[:id])
  end

  # POST /linkedin_transitions
  # POST /linkedin_transitions.json
  def create
    @linkedin_transition = LinkedinTransition.new(params[:linkedin_transition])

    respond_to do |format|
      if @linkedin_transition.save
        format.html { redirect_to @linkedin_transition, notice: 'Linkedin transition was successfully created.' }
        format.json { render json: @linkedin_transition, status: :created, location: @linkedin_transition }
      else
        format.html { render action: "new" }
        format.json { render json: @linkedin_transition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /linkedin_transitions/1
  # PUT /linkedin_transitions/1.json
  def update
    @linkedin_transition = LinkedinTransition.find(params[:id])

    respond_to do |format|
      if @linkedin_transition.update_attributes(params[:linkedin_transition])
        format.html { redirect_to @linkedin_transition, notice: 'Linkedin transition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @linkedin_transition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linkedin_transitions/1
  # DELETE /linkedin_transitions/1.json
  def destroy
    @linkedin_transition = LinkedinTransition.find(params[:id])
    @linkedin_transition.destroy

    respond_to do |format|
      format.html { redirect_to linkedin_transitions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/linkedin_transitions_helper.rb
module LinkedinTransitionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "DerivativeD", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to('Admin', users_path) %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "App_Name" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "App_Name" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/linkedin_transitions/_form.html.erb
<%= form_for(@linkedin_transition) do |f| %>
  <% if @linkedin_transition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@linkedin_transition.errors.count, "error") %> prohibited this linkedin_transition from being saved:</h2>

      <ul>
      <% @linkedin_transition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profile_id %><br />
    <%= f.number_field :profile_id %>
  </div>
  <div class="field">
    <%= f.label :from_company_id %><br />
    <%= f.number_field :from_company_id %>
  </div>
  <div class="field">
    <%= f.label :from_company_name %><br />
    <%= f.text_field :from_company_name %>
  </div>
  <div class="field">
    <%= f.label :from_company_position %><br />
    <%= f.text_field :from_company_position %>
  </div>
  <div class="field">
    <%= f.label :from_company_industry %><br />
    <%= f.number_field :from_company_industry %>
  </div>
  <div class="field">
    <%= f.label :to_company_id %><br />
    <%= f.number_field :to_company_id %>
  </div>
  <div class="field">
    <%= f.label :to_company_name %><br />
    <%= f.text_field :to_company_name %>
  </div>
  <div class="field">
    <%= f.label :to_company_position %><br />
    <%= f.text_field :to_company_position %>
  </div>
  <div class="field">
    <%= f.label :to_company_industry %><br />
    <%= f.number_field :to_company_industry %>
  </div>
  <div class="field">
    <%= f.label :joined_date %><br />
    <%= f.date_select :joined_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/linkedin_transitions/edit.html.erb
<h1>Editing linkedin_transition</h1>

<%= render 'form' %>

<%= link_to 'Show', @linkedin_transition %> |
<%= link_to 'Back', linkedin_transitions_path %>

app/views/linkedin_transitions/index.html.erb
<h1>Listing linkedin_transitions</h1>

<table>
  <tr>
    <th>Profile</th>
    <th>From company</th>
    <th>From company name</th>
    <th>From company position</th>
    <th>From company industry</th>
    <th>To company</th>
    <th>To company name</th>
    <th>To company position</th>
    <th>To company industry</th>
    <th>Joined date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @linkedin_transitions.each do |linkedin_transition| %>
  <tr>
    <td><%= linkedin_transition.profile_id %></td>
    <td><%= linkedin_transition.from_company_id %></td>
    <td><%= linkedin_transition.from_company_name %></td>
    <td><%= linkedin_transition.from_company_position %></td>
    <td><%= linkedin_transition.from_company_industry %></td>
    <td><%= linkedin_transition.to_company_id %></td>
    <td><%= linkedin_transition.to_company_name %></td>
    <td><%= linkedin_transition.to_company_position %></td>
    <td><%= linkedin_transition.to_company_industry %></td>
    <td><%= linkedin_transition.joined_date %></td>
    <td><%= link_to 'Show', linkedin_transition %></td>
    <td><%= link_to 'Edit', edit_linkedin_transition_path(linkedin_transition) %></td>
    <td><%= link_to 'Destroy', linkedin_transition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Linkedin transition', new_linkedin_transition_path %>

app/views/linkedin_transitions/new.html.erb
<h1>New linkedin_transition</h1>

<%= render 'form' %>

<%= link_to 'Back', linkedin_transitions_path %>

app/views/linkedin_transitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Profile:</b>
  <%= @linkedin_transition.profile_id %>
</p>

<p>
  <b>From company:</b>
  <%= @linkedin_transition.from_company_id %>
</p>

<p>
  <b>From company name:</b>
  <%= @linkedin_transition.from_company_name %>
</p>

<p>
  <b>From company position:</b>
  <%= @linkedin_transition.from_company_position %>
</p>

<p>
  <b>From company industry:</b>
  <%= @linkedin_transition.from_company_industry %>
</p>

<p>
  <b>To company:</b>
  <%= @linkedin_transition.to_company_id %>
</p>

<p>
  <b>To company name:</b>
  <%= @linkedin_transition.to_company_name %>
</p>

<p>
  <b>To company position:</b>
  <%= @linkedin_transition.to_company_position %>
</p>

<p>
  <b>To company industry:</b>
  <%= @linkedin_transition.to_company_industry %>
</p>

<p>
  <b>Joined date:</b>
  <%= @linkedin_transition.joined_date %>
</p>


<%= link_to 'Edit', edit_linkedin_transition_path(@linkedin_transition) %> |
<%= link_to 'Back', linkedin_transitions_path %>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline' %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
	  <thead>
      <tr>
          <th>Username</th>
          <th>Email</th>
          <th>Registered</th>
          <th>Role</th>
          <th></th>
          <th></th>                                      
      </tr>
  </thead>   
  <tbody>
  <% @users.each do |user| %>
    <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.to_date %></td>
        <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
        <td>
          <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
          <%= render user %>
        </td>
        <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>                                       
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>